name       : rhythmbox
version    : 3.4.7
release    : 51
source     :
    - https://download.gnome.org/sources/rhythmbox/3.4/rhythmbox-3.4.7.tar.xz : 2f6d56c13fc1a64c534f500788fb482936ce547b343ed90c67de1f2bce0cfa7e
license    : GPL-2.0-only
component  : multimedia.audio
summary    : Music playing application
description: |
    Music playing application for GNOME
builddeps  :
    - pkgconfig(avahi-client)
    - pkgconfig(clutter-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(sm)
    - pkgconfig(tdb)
    - pkgconfig(totem-plparser)
    - pkgconfig(webkit2gtk-4.0)
    - desktop-file-utils
    - gtk-doc
    - itstool
    - vala
    - yelp-tools
rundeps    :
    - python-gobject
setup      : |
    %meson_configure 
build      : |
    %ninja_build
install    : |
    %ninja_install
