name       : rhythmbox
version    : '3.4'
release    : 17
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/rhythmbox/3.4/rhythmbox-3.4.tar.xz : ef8592aa0ee184e40d23a5007885c32585325b462e78cb0ff95181540f39878c
license    :
    - GPL-2.0
component  : multimedia.audio
summary    : Music playing application
description: |
    Music playing application for GNOME
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(sm)
    - pkgconfig(tdb)
    - pkgconfig(totem-plparser)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
    - vala
rundeps    :
    - python3-gobject
setup      : |
    %patch -p1 < $pkgfiles/0001-rb-application-Ensure-paramater-nullability-is-known.patch
    %configure --disable-static \
               --enable-python \
               --enable-libnotify \
               --disable-rpath \
               --with-webkit \
               --enable-vala \
               --with-mtp \
               --with-libsecret
build      : |
    %make
install    : |
    %make_install
