name       : rhythmbox
version    : 3.4.4
release    : 42
source     :
    - git|https://gitlab.gnome.org/GNOME/rhythmbox.git : 0e3784d121a1b70aa671b41fa634c08ff2110d8d
license    : GPL-2.0-only
component  : multimedia.audio
summary    : Music playing application
description: |
    Music playing application for GNOME
builddeps  :
    - pkgconfig(avahi-client)
    - pkgconfig(clutter-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(sm)
    - pkgconfig(tdb)
    - pkgconfig(totem-plparser)
    - pkgconfig(webkit2gtk-4.0)
    - gtk-doc
    - itstool
    - vala
    - yelp-tools
rundeps    :
    - python-gobject
setup      : |
    NOCONFIGURE=1 %autogen
    %configure --disable-rpath \
        --disable-static \
        --enable-grilo \
        --enable-python \
        --enable-libnotify \
        --enable-vala \
        --with-libsecret \
        --with-mtp
build      : |
    %make
install    : |
    %make_install
