name       : rhythmbox
version    : 3.4.1
release    : 21
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/rhythmbox/3.4/rhythmbox-3.4.1.tar.xz : 039f86661cba495f9429df6572fa79e68279635809e52fa0d19f57e8db8341b6
license    : GPL-2.0
component  : multimedia.audio
summary    : Music playing application
description: |
    Music playing application for GNOME
builddeps  :
    - pkgconfig(avahi-client)
    - pkgconfig(clutter-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libdmapsharing-3.0)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(sm)
    - pkgconfig(tdb)
    - pkgconfig(totem-plparser)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
    - vala
rundeps    :
    - python3-gobject
setup      : |
    %configure --disable-rpath \
               --disable-static \
               --enable-daap \
               --enable-python \
               --enable-libnotify \
               --enable-vala \
               --with-libsecret \
               --with-mtp \
               --with-webkit
build      : |
    %make
install    : |
    %make_install
