name       : rhythmbox
version    : 3.4.6
release    : 46
source     :
    - https://download.gnome.org/sources/rhythmbox/3.4/rhythmbox-3.4.6.tar.xz : f9568210ce55e411e929c8fb95e111a211dbd19cc47f578f291c5d319b5eb034
license    : GPL-2.0-only
component  : multimedia.audio
summary    : Music playing application
description: |
    Music playing application for GNOME
builddeps  :
    - pkgconfig(avahi-client)
    - pkgconfig(clutter-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(sm)
    - pkgconfig(tdb)
    - pkgconfig(totem-plparser)
    - pkgconfig(webkit2gtk-4.0)
    - desktop-file-utils
    - gtk-doc
    - itstool
    - vala
    - yelp-tools
rundeps    :
    - python-gobject
setup      : |
    %meson_configure 
build      : |
    %ninja_build
install    : |
    %ninja_install
