name        : rhythmbox
version     : 3.3
release     : 10
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/rhythmbox/3.3/rhythmbox-3.3.tar.xz : 5299ac4d3dbc4e281aa422e957b3a7741207512ae051fdfc8159e1322b486859
license     :
    - GPL-2.0
summary     : Music playing application for GNOME
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(tdb)
    - pkgconfig(totem-plparser)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(ice)
    - pkgconfig(sm)
    - pkgconfig(libnotify)
    - pkgconfig(clutter-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.4)
    - pkgconfig(webkitgtk-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libmtp)
    - itstool
    - vala
rundeps     :
    - python3-gobject
description : |
    Music playing application for GNOME
setup      : |
    %configure --disable-static \
               --enable-python \
               --enable-libnotify \
               --disable-rpath \
               --with-webkit \
               --enable-vala \
               --with-mtp \
               --with-libsecret
build      : |
    %make
install    : |
    %make_install
