name        : rhythmbox
version     : 3.2.1
release     : 9
source     :
    - http://ftp.gnome.org/pub/gnome/sources/rhythmbox/3.2/rhythmbox-3.2.1.tar.xz : bf43ca4f5b7531751241f5e67eaba7da6d9748dd827a600eedf9444961537938
license     :
    - GPL-2.0
summary     : Music playing application for GNOME
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(tdb)
    - pkgconfig(totem-plparser)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(ice)
    - pkgconfig(sm)
    - pkgconfig(libnotify)
    - pkgconfig(clutter-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.4)
    - pkgconfig(webkitgtk-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libmtp)
    - itstool
    - vala
rundeps     :
    - python3-gobject
description : |
    Music playing application for GNOME
setup      : |
    %configure --disable-static \
               --enable-python \
               --enable-libnotify \
               --disable-rpath \
               --with-webkit \
               --enable-vala \
               --with-mtp \
               --with-libsecret
build      : |
    %make
install    : |
    %make_install
