name      : rhythmbox
version    : 3.4.2
release    : 23
source    :
    - https://download.gnome.org/sources/rhythmbox/3.4/rhythmbox-3.4.2.tar.xz : c27622fb7658d3c8e935937a562ebd8a65f5316a12694d6a06cb17f790b6ec43
license    : GPL-2.0
component  : multimedia.audio
summary    : Music playing application
description: |
    Music playing application for GNOME
builddeps  :
    - pkgconfig(avahi-client)
    - pkgconfig(clutter-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libdmapsharing-3.0)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(sm)
    - pkgconfig(tdb)
    - pkgconfig(totem-plparser)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
    - vala
rundeps    :
    - python3-gobject
setup      : |
    %configure --disable-rpath \
        --disable-static \
        --enable-daap \
        --enable-grilo \
        --enable-python \
        --enable-libnotify \
        --enable-vala \
        --with-libsecret \
        --with-mtp
build      : |
    %make
install    : |
    %make_install
