name        : rhythmbox
version     : 3.3.1
release     : 14
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/rhythmbox/3.3/rhythmbox-3.3.1.tar.xz : ef3c1023ed05025cd2aaed9ca83bf9bc557e4e8da660d7f31c5e3158fda93c61
license     :
    - GPL-2.0
component   : desktop.gnome
summary     : Music playing application for GNOME
builddeps   :
    - pkgconfig(clutter-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(sm)
    - pkgconfig(tdb)
    - pkgconfig(totem-plparser)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
    - vala
rundeps     :
    - python3-gobject
description : |
    Music playing application for GNOME
setup      : |
    %configure --disable-static \
               --enable-python \
               --enable-libnotify \
               --disable-rpath \
               --with-webkit \
               --enable-vala \
               --with-mtp \
               --with-libsecret
build      : |
    %make
install    : |
    %make_install
